/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package siman;

import bd.ConexionBD;
import com.placeholder.PlaceHolder;
import java.awt.Color;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import utilidades.Queries;

/**
 *
 * @author Carlos
 */
public class Reportes extends javax.swing.JFrame {

    Statement stmt = null;
    Connection con = null;
    ArrayList<String> colaboradores = new ArrayList<String>();
    int idColaborador;
    int idSucursal;
    int cifrasDecimales;
    String nombreColaborador;
    String nombreSucursal;
    int idColaboradorActivo;

    /**
     * Creates new form Sucursales
     */
    public Reportes(String nombreUsuario, int idColaborador) throws SQLException {
        initComponents();
        informacionGeneral();
        lbl_nombreUsuario.setText(nombreUsuario);
        this.con = ConexionBD.obtenerConexion();
        this.idColaboradorActivo = idColaborador;
        llenarTransportistas();
    }

    public Reportes() throws SQLException {
        initComponents();
        informacionGeneral();
        lbl_nombreUsuario.setText("carlos.chamorro");
        this.idColaboradorActivo = 1;
        this.con = ConexionBD.obtenerConexion();
        llenarTransportistas();
    }
    
    private void llenarTransportistas() {
        ArrayList<String> lista = new ArrayList<String>();
        try {
            lista = new Queries().llenarTransportistas();
            for (int i = 0; i < lista.size(); i++) {
                cmb_transportistas.addItem(lista.get(i));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Asignaciones.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void informacionGeneral() {
        this.setTitle("Sucursales");
        this.setLocationRelativeTo(null);
        this.setIconImage(new ImageIcon(getClass().getResource("../Img/icono.png")).getImage());
    }


    private void habilitarAccionesBuscar() {
        btn_generar.setEnabled(false);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jpn_principal = new javax.swing.JPanel();
        lbl_nombreUsuario = new javax.swing.JLabel();
        btn_generar = new javax.swing.JButton();
        lbl_home = new javax.swing.JLabel();
        lbl_usuario = new javax.swing.JLabel();
        lbl_tituloReportes = new javax.swing.JLabel();
        lbl_limpiar = new javax.swing.JLabel();
        cmb_transportistas = new javax.swing.JComboBox<>();
        jdt_fechaInicial = new com.toedter.calendar.JDateChooser();
        jdt_fechaFinal = new com.toedter.calendar.JDateChooser();
        lbl_fechaInicial = new javax.swing.JLabel();
        lbl_fechaFinal = new javax.swing.JLabel();
        lbl_transportista = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        kGradientPanel1.setkEndColor(new java.awt.Color(40, 74, 172));
        kGradientPanel1.setkStartColor(new java.awt.Color(205, 63, 145));
        kGradientPanel1.setkTransparentControls(false);
        kGradientPanel1.setPreferredSize(new java.awt.Dimension(1319, 821));

        jpn_principal.setBackground(new java.awt.Color(255, 255, 255));

        lbl_nombreUsuario.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        lbl_nombreUsuario.setText("Nombre de Usuario");

        btn_generar.setBackground(new java.awt.Color(205, 63, 145));
        btn_generar.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        btn_generar.setForeground(new java.awt.Color(255, 255, 255));
        btn_generar.setText("Generar");
        btn_generar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_generar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_generarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_generarMouseExited(evt);
            }
        });
        btn_generar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_generarActionPerformed(evt);
            }
        });

        lbl_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/home.png"))); // NOI18N
        lbl_home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_homeMousePressed(evt);
            }
        });

        lbl_usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/profile.png"))); // NOI18N
        lbl_usuario.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lbl_tituloReportes.setFont(new java.awt.Font("Roboto Black", 0, 48)); // NOI18N
        lbl_tituloReportes.setText("Reportes");

        lbl_limpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/clean.png"))); // NOI18N
        lbl_limpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_limpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_limpiarMouseClicked(evt);
            }
        });

        cmb_transportistas.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        cmb_transportistas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione al transportista" }));
        cmb_transportistas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        cmb_transportistas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cmb_transportistas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_transportistasActionPerformed(evt);
            }
        });

        jdt_fechaInicial.setDateFormatString("dd/MM/yyyy");
        jdt_fechaInicial.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jdt_fechaInicial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jdt_fechaInicialMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jdt_fechaInicialMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jdt_fechaInicialMousePressed(evt);
            }
        });

        jdt_fechaFinal.setDateFormatString("dd/MM/yyyy");
        jdt_fechaFinal.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jdt_fechaFinal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jdt_fechaFinalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jdt_fechaFinalMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jdt_fechaFinalMousePressed(evt);
            }
        });

        lbl_fechaInicial.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        lbl_fechaInicial.setText("Fecha inicial");

        lbl_fechaFinal.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        lbl_fechaFinal.setText("Fecha final");

        lbl_transportista.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        lbl_transportista.setText("Transportista");

        javax.swing.GroupLayout jpn_principalLayout = new javax.swing.GroupLayout(jpn_principal);
        jpn_principal.setLayout(jpn_principalLayout);
        jpn_principalLayout.setHorizontalGroup(
            jpn_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpn_principalLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jpn_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpn_principalLayout.createSequentialGroup()
                        .addComponent(lbl_usuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_nombreUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_home)
                        .addGap(21, 21, 21))
                    .addGroup(jpn_principalLayout.createSequentialGroup()
                        .addGroup(jpn_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpn_principalLayout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addGroup(jpn_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbl_fechaFinal)
                                    .addComponent(lbl_fechaInicial))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jpn_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jdt_fechaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jdt_fechaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpn_principalLayout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addGroup(jpn_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_generar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpn_principalLayout.createSequentialGroup()
                                        .addComponent(lbl_transportista)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cmb_transportistas, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)))))
                        .addGap(18, 18, 18)
                        .addComponent(lbl_limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(33, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpn_principalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_tituloReportes)
                .addGap(280, 280, 280))
        );
        jpn_principalLayout.setVerticalGroup(
            jpn_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpn_principalLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jpn_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpn_principalLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(lbl_nombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbl_home, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(lbl_tituloReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(jpn_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpn_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmb_transportistas, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_transportista, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jpn_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jdt_fechaInicial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_fechaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpn_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_fechaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jdt_fechaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(btn_generar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(146, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(297, 297, 297)
                .addComponent(jpn_principal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(330, Short.MAX_VALUE))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jpn_principal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1395, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_generarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_generarMouseEntered
        btn_generar.setBackground(new Color(156, 2, 91));
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_generarMouseEntered

    private void btn_generarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_generarMouseExited
        btn_generar.setBackground(new Color(205, 63, 145));
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_generarMouseExited

    private void lbl_homeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_homeMousePressed

        try {
            this.dispose();
            Principal principal;
            principal = new Principal(lbl_nombreUsuario.getText(), idColaboradorActivo);
            principal.setVisible(true);
            
        } catch (SQLException ex) {
            Logger.getLogger(Reportes.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        // TODO add your handling code here:
        
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_homeMousePressed

    private void lbl_limpiarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_limpiarMouseClicked
        //restablecer();
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_limpiarMouseClicked

    private void cmb_transportistasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_transportistasActionPerformed

        if(!cmb_transportistas.getSelectedItem().toString().equals("Seleccione al transportista")){
            /*limpiarSucursales();
            llenarSucursales();
            String informacionTransportista = cmb_transportistas.getSelectedItem().toString();
            String reemplazarInformacionTransportistas = informacionTransportista.replace("(", "|");
            String informacionTransportistaFormateada = reemplazarInformacionTransportistas.replace(")", "|");
            String [] partesInformacionTransportistas = informacionTransportistaFormateada.split("\\|");
            String numeroIdentidadTransportista = partesInformacionTransportistas[1].trim();
            idTransportista = capturarIdTransportista(numeroIdentidadTransportista);
            tarifa = llenarTarifa(numeroIdentidadTransportista);
            txt_tarifa.setText(Double.toString(tarifa));
            cmb_transportistas.setEnabled(false);
            btn_limpiar.setEnabled(true);
            jdt_fechaViaje.setEnabled(true);
            lbl_iniciar.setEnabled(true);*/
        }
    }//GEN-LAST:event_cmb_transportistasActionPerformed

    private void jdt_fechaInicialMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jdt_fechaInicialMouseEntered
        if(jdt_fechaInicial.getCalendar()!=null){
            //lbl_iniciar.setEnabled(true);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jdt_fechaInicialMouseEntered

    private void jdt_fechaInicialMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jdt_fechaInicialMouseExited
        if(jdt_fechaInicial.getCalendar()!=null){
            //lbl_iniciar.setEnabled(true);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jdt_fechaInicialMouseExited

    private void jdt_fechaInicialMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jdt_fechaInicialMousePressed
        JOptionPane.showMessageDialog(null, "Click","Viaje activo",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jdt_fechaInicialMousePressed

    private void jdt_fechaFinalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jdt_fechaFinalMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jdt_fechaFinalMouseEntered

    private void jdt_fechaFinalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jdt_fechaFinalMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jdt_fechaFinalMouseExited

    private void jdt_fechaFinalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jdt_fechaFinalMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jdt_fechaFinalMousePressed

    private void btn_generarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_generarActionPerformed
        
    }//GEN-LAST:event_btn_generarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new Reportes().setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(Reportes.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_generar;
    private javax.swing.JComboBox<String> cmb_transportistas;
    private com.toedter.calendar.JDateChooser jdt_fechaFinal;
    private com.toedter.calendar.JDateChooser jdt_fechaInicial;
    private javax.swing.JPanel jpn_principal;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel lbl_fechaFinal;
    private javax.swing.JLabel lbl_fechaInicial;
    private javax.swing.JLabel lbl_home;
    private javax.swing.JLabel lbl_limpiar;
    private javax.swing.JLabel lbl_nombreUsuario;
    private javax.swing.JLabel lbl_tituloReportes;
    private javax.swing.JLabel lbl_transportista;
    private javax.swing.JLabel lbl_usuario;
    // End of variables declaration//GEN-END:variables
}
